### ISSUE TITLE
[connectivity_package-0.9.3] Pausing connectivity probe throws PlatformException

### ISSUE THREAD

**Issue by koenniem** [cph-cachet/carp.sensing-flutter#119]
## Device / Emulator and OS
* Device: Pixel 3
* OS: Android API 29

## Describe the bug
When pausing the connectivity probe, a PlatformException is thrown. 

## To reproduce
Run CAMS example app with connectivity probe enabled and press the pause button.

## Expected behavior 
The probe is paused

## Actual behavior
The stream is unhandled, an exception is thrown:

```dart
════════ Exception caught by services library ══════════════════════════════════════════════════════
The following PlatformException was thrown while de-activating platform stream on channel plugins.flutter.io/connectivity_status:
PlatformException(error, NetworkCallback was not registered, null, null)

When the exception was thrown, this was the stack: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:552:29)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by bardram** [comment]
Seems to be fixed in `carp_connectivity_package` v. 0.10.0
