### ISSUE TITLE
Issue in CARP participation service

### ISSUE THREAD

**Issue by LarsRefsgaard** [cph-cachet/carp.sensing-flutter#352]
Stacktrace when trying to run `getActiveParticipationInvitations`:
```
[log] [CAMS DEBUG] REQUEST: https://carp.computerome.dk/dev/api/participation-service
      {
       "__type": "dk.cachet.carp.deployments.infrastructure.ParticipationServiceRequest.GetActiveParticipationInvitations",
       "apiVersion": "1.0",
       "accountId": "5e22daa7-1053-44c1-b1fe-3bbff0e31df3"
      }

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: SerializationException - A 'fromJson' function was not found in the FromJsonFactory for the type 'dk.cachet.carp.common.application.devices.WebBrowser'. Register a Serializable class using the 'FromJsonFactory().register()' method.
If you are using CARP Mobile Sensing, you can ensure json initialization by calling'CarpMobileSensing.ensureInitialized()' as part of your main method.
#0      FromJsonFactory.fromJson (package:carp_serializable/carp_serializable.dart:180)
carp_serializable.dart:1
#1      new PrimaryDeviceConfiguration.fromJson (package:carp_core/common/application/devices/device_configuration.dart:124)
device_configuration.dart:1
#2      _$AssignedPrimaryDeviceFromJson (package:carp_core/deployment/carp_core_deployment.g.dart:118)
carp_core_deployment.g.dart:1
#3      new AssignedPrimaryDevice.fromJson (package:carp_core/deployment/application/device_deployment.dart:221)
device_deployment.dart:1
#4      _$ActiveParticipationInvitationFromJson.<anonymous closure> (package:carp_core/deployment/carp_core_deployment.g.dart:279)
carp_core_deployment.g.dart:1
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:344)
#7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#9      new List.of (dart:core-patch/array_patch.dart:47)
#10     ListIterable.toList (dart:_internal/iterable.dart:214)
#11     _$ActiveParticipationInvitationFromJson (package:carp_core/deployment/carp_core_deployment.g.dart:280)
carp_core_deployment.g.dart:1
#12     new ActiveParticipationInvitation.fromJson (package:carp_core/deployment/application/users.dart:114)
users.dart:1
#13     CarpParticipationService.getActiveParticipationInvitations.<anonymous closure> (package:carp_webservices/carp_services/participation_service.dart:49)
participation_service.dart:1
#14     MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#15     ListIterator.moveNext (dart:_internal/iterable.dart:344)
#16     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#17     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#18     new List.of (dart:core-patch/array_patch.dart:47)
#19     ListIterable.toList (dart:_internal/iterable.dart:214)
#20     CarpParticipationService.getActiveParticipationInvitations (package:carp_webservices/carp_services/participation_service.dart:51)
participation_service.dart:1
<asynchronous suspension>
#21     InvitationsListViewModel.invitations (package:carp_study_app/view_models/invitations_list_model.dart:6)
invitations_list_model.dart:1
<asynchronous suspension>
#22     InvitationListPage.build.<anonymous closure>.<anonymous closure> (package:carp_study_app/ui/pages/invitation_list_page.dart:54)
invitation_list_page.dart:1
<asynchronous suspension>

[log] [CAMS DEBUG] RESPONSE: 200
      [{"participation":{"studyDeploymentId":"4b2811f1-4b32-4c00-bc05-c262789b5c1e","assignedRoles":{"__type":"dk.cachet.carp.common.application.users.AssignedTo.Roles","roleNames":["Father"]},"participantId":"870dafb5-a18a-4f07-bf4a-7b681eeb9880"},"invitation":{"name":"Study app","applicationData":"36b2e26c-f45f-4f58-bdf4-bd3e3ebf95d4"},"assignedDevices":[{"device":{"__type":"dk.cachet.carp.common.application.devices.Smartphone","isPrimaryDevice":true,"roleName":"Father's Phone"},"registration":{"__type":"dk.cachet.carp.common.application.devices.DefaultDeviceRegistration","registrationCreatedOn":"2023-10-09T10:12:01.647058Z","deviceDisplayName":"4E16ACDF-A0EF-46D4-96D4-7CC1EAE1CE11 - iPhone APPLE [SDK 23.0.0]","deviceId":"4E16ACDF-A0EF-46D4-96D4-7CC1EAE1CE11"}}]},{"participation":{"studyDeploymentId":"4b2811f1-4b32-4c00-bc05-c262789b5c1e","assignedRoles":{"__type":"dk.cachet.carp.common.application.users.AssignedTo.Roles","roleNames":["Mother"]},"participantId":"3a18db73-2f7c-48de-a58e-a9e8a5010c9e"},"invitation":{"name":"Study app","applicationData":"36b2e26c-f45f-4f58-bdf4-bd3e3ebf95d4"},"assignedDevices":[{"device":{"__type":"dk.cachet.carp.common.application.devices.Smartphone","isPrimaryDevice":true,"roleName":"Mother's Phone"},"registration":{"__type":"dk.cachet.carp.common.application.devices.DefaultDeviceRegistration","registrationCreatedOn":"2023-10-11T14:28:13.027782Z","deviceDisplayName":"7E334622-B085-4530-8241-27A85C8035B3 - iPhone APPLE [SDK 23.0.0]","deviceId":"7E334622-B085-4530-8241-27A85C8035B3"}}]},{"participation":{"studyDeploymentId":"f8553d2e-2d4f-48e7-b54b-a98e059f5341","assignedRoles":{"__type":"dk.cachet.carp.common.application.users.AssignedTo.Roles","roleNames":["Version 1"]},"participantId":"ecf3029d-7afe-4c9e-8292-a11dfcbb188c"},"invitation":{"name":"The ICAT Test","description":"Hello victims! Welcome to the ICAT test. ","applicationData":"133cb51b-9403-4982-8ce1-8aa128598b81"},"assignedDevices":[{"device":{"__type":"dk.cachet.carp.common.application.devices.WebBrowser","roleName":"ICAT Web Browser","isPrimaryDevice":true,"defaultSamplingConfiguration":{}}}]},{"participation":{"studyDeploymentId":"f8553d2e-2d4f-48e7-b54b-a98e059f5341","assignedRoles":{"__type":"dk.cachet.carp.common.application.users.AssignedTo.Roles","roleNames":["Version 1"]},"participantId":"2dfdaf36-b7ea-45b5-9721-27dd038e8269"},"invitation":{"name":"The ICAT Test","description":"Hello victims! Welcome to the ICAT test. ","applicationData":"133cb51b-9403-4982-8ce1-8aa128598b81"},"assignedDevices":[{"device":{"__type":"dk.cachet.carp.common.application.devices.WebBrowser","roleName":"ICAT Web Browser","isPrimaryDevice":true,"defaultSamplingConfiguration":{}}}]},{"participation":{"studyDeploymentId":"240ba212-1030-41bc-a5b7-f32bd43a366f","assignedRoles":{"__type":"dk.cachet.carp.common.application.users.AssignedTo.Roles","roleNames":["Participant"]},"participantId":"9cf0844a-7bb8-4af6-9364-50268dae2b92"},"invitation":{"name":"CATCH Test","description":"Welcome to the Testing Phase of the CATCH Data Collection Study","applicationData":"b8a10d9a-1cf0-48ae-a148-1d6ac086368d"},"assignedDevices":[{"device":{"__type":"dk.cachet.carp.common.application.devices.Smartphone","isPrimaryDevice":true,"roleName":"Primary Phone"}}]},{"participation":{"studyDeploymentId":"240ba212-1030-41bc-a5b7-f32bd43a366f","assignedRoles":{"__type":"dk.cachet.carp.common.application.users.AssignedTo.Roles","roleNames":["Participant"]},"participantId":"a1ac2187-3139-4db2-9f3c-35e73ba237e9"},"invitation":{"name":"CATCH Test","description":"Welcome to the Testing Phase of the CATCH Data Collection Study","applicationData":"b8a10d9a-1cf0-48ae-a148-1d6ac086368d"},"assignedDevices":[{"device":{"__type":"dk.cachet.carp.common.application.devices.Smartphone","isPrimaryDevice":true,"roleName":"Primary Phone"}}]},{"participation":{"studyDeploymentId":"240ba212-1030-41bc-a5b7-f32bd43a366f","assignedRoles":{"__type":"dk.cachet.carp.common.application.users.AssignedTo.Roles","roleNames":["Participant"]},"participantId":"3b1b8ccb-ce64-4b9e-be9a-79c00b8db9dc"},"invitation":{"name":"CATCH Test","description":"Welcome to the Testing Phase of the CATCH Data Collection Study","applicationData":"b8a10d9a-1cf0-48ae-a148-1d6ac086368d"},"assignedDevices":[{"device":{"__type":"dk.cachet.carp.common.application.devices.Smartphone","isPrimaryDevice":true,"roleName":"Primary Phone"}}]}]
```

Quite possibly related to being invited to the ICAT study, as the error stems from not being able to serialize 'WebBrowser'?

**Comment by bardram** [comment]
Fixed and published as version: 1.3.1
